using Aqua

# Many ambiguities in dependencies

#Aqua.test_all(DimensionReductionRegression)
#Aqua.test_ambiguities(DimensionReductionRegression)
Aqua.test_unbound_args(DimensionReductionRegression)
Aqua.test_deps_compat(DimensionReductionRegression)
Aqua.test_undefined_exports(DimensionReductionRegression)
Aqua.test_project_extras(DimensionReductionRegression)
Aqua.test_stale_deps(DimensionReductionRegression)
Aqua.test_deps_compat(DimensionReductionRegression)
Aqua.test_piracies(DimensionReductionRegression)
Aqua.test_persistent_tasks(DimensionReductionRegression)
